config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  namespace :editor do
    resources :flats, except: [:index, :show] do
      post '/share_on_vk', to: 'flats#share_on_vk', on: :member
      post '/feature', to: 'flats#feature', on: :member
      post '/rent', to: 'flats#rent', on: :member
      post '/unpublish', to: 'flats#unpublish', on: :member
    end
  end

  resources :flats do
    get '/match', to: 'flats#mark', on: :member
    get '/share', to: 'flats#share', on: :member
  end

  resources :tickets

  resources :clients
  resources :searches
  resources :requests

  root 'welcome#index'

  get "/:id", to: "pages#show", as: :page
end

app/models/flat.rb
require 'open-uri'

class Flat < ActiveRecord::Base
  include Shareable

  has_many :photos, dependent: :destroy

  has_many :requests
  has_many :clients, through: :requests

  accepts_nested_attributes_for :photos

  default_scope -> { where(published: true, rented: false).order('created_at desc') }
  scope :published, -> { where(published: true) }
  scope :recent, -> { limit(12) }
  scope :featured, -> { where(featured: true) }
  scope :available, -> { where(rented: false) }

  geocoded_by :location
  after_validation :geocode, if: :address_changed?
  after_validation :geocode, if: :part_changed?

  def self.mark_all_photos
    all.each do |flat|
      flat.mark_photos
    end
  end

  def title
    "#{address}, #{part}"
  end

  def cover
    if cover_id.present? && photos.exists?(cover_id)
      photos.find(cover_id)
    else
      photos.last
    end
  end

  def description
    description_ru.presence ? description_ru : super
  end

  def location
    "#{address}, #{part}"
  end

  def mark_photos
    photos.each do |photo|
      photo.mark!
    end
  end

  def ensure_availability
    return false unless external_source_id.present?

    external_source_page = Nokogiri::HTML(open("http://www.feelhome.cz/pronajem/detail/#{external_source_id}/"))

    if (external_source_page.css('#detailprice').text.strip =~ /pronajato/)
      update_column(:rented, true)
      id
    else
      nil
    end
  end
end

app/controllers/editor/flats_controller.rb
class Editor::FlatsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_flat

  def share_on_vk
    @flat.share_on_vk

    render nothing: true, status: :ok
  end

  def feature
    @flat.update_column(:featured, true)

    render nothing: true, status: :ok
  end

  def rent
    @flat.update_column(:rented, true)

    render nothing: true, status: :ok
  end

  def unpublish
    @flat.update_column(:published, false)

    render nothing: true, status: :ok
  end

private

  def flat_params
    params.require(:flat).permit(:featured, :rented, :published)
  end

  def set_flat
    @flat = Flat.unscoped.find(params[:id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:mark, :share]
  before_action :set_unscoped_flat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @flats = Flat.all.page(params[:page])
  end

  def new
    @flat = Flat.new
    @flat.published = false
    @flat.save

    redirect_to edit_flat_path(@flat)
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flat_url(@flat)
    else
      render action: :new
    end
  end

  def mark
    @flat.photos.each do |photo|
      photo.mark!
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      respond_to do |format|
        format.html { redirect_to flat_url(@flat) }
        format.json { render json: @flat.to_json }
      end
    else
      respond_to do |format|
        format.html { render action: :edit }
        format.json
      end
    end
  end

  def show
    @request = @flat.requests.build
  end

  def share
    @flat.share_on_vk

    redirect_to flat_url(@flat)
  end

private

  def flat_params
    params.require(:flat).permit(:address, :part, :rooms, :rent, :area, :description, :description_ru, :published, :utility_included, :featured, :rented, :external_source_id, :cover_id, { photos_attributes: [:file] })
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def set_unscoped_flat
    @flat = Flat.unscoped.find(params[:id])
  end
end

app/helpers/editor/flats_helper.rb
module Editor::FlatsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<%= content_tag_for :section, flat do %>
  <h3><%= link_to_unless_current "#{flat.address}, #{flat.rooms}", flat_path(flat) %></h3>

  <div><%= number_to_currency(flat.rent, unit: 'CZK', format: '%n %u', precision: 0) %></div>
  <div><%= "#{flat.area}m<sup>2</sup>".html_safe %></div>

  <%= simple_format flat.description %>

  <% flat.photos.each do |photo| %>
    <%= image_tag photo.file.url %>
  <% end %>
<% end %>

app/views/flats/_form.html.erb
<%= simple_form_for @flat, html: { multipart: true, data: { flat_id: @flat.id } } do |f| %>
  <%= f.input :published, as: :hidden %>

  <%= f.input :address, placeholder: 'Kroftova 13', autofocus: true %>
  <%= f.input :part, placeholder: 'Praha 2, Vyšehrad' %>

  <fieldset class="form__row">
    <%= f.input :rooms, placeholder: '3+1, 1+kk, 2+kk, etc.', wrapper_html: { class: 'input--half' } %>
    <%= f.input :area, placeholder: '86m²', wrapper_html: { class: 'input--half' } %>
  </fieldset>

  <%= f.input :rent, placeholder: '18.000' %>
  <%= f.input :utility_included %>
  <%= f.input :featured %>
  <%= f.input :rented %>
  <%= f.input :external_source_id %>
  <%= f.input :description, as: :text %>
  <%= f.input :description_ru, as: :text %>

  <%#= f.simple_fields_for :photos do |p| %>
    <%#= p.input :file, label: 'Photos' %>
  <%# end %>

  <div class="new-flat__photos__placeholder js-dropzone js-dropzone-preview">
    <span><i class="ss-icon">attach</i><%= t('flats.drag_photos_html', href: link_to(t('flats.drag_photos_href'), '')) %></span>

    <div class="new-flat__photos"></div>
  </div>

  <% if @flat.published? %>
    <%= f.label 'Обложка' %>
    <ul class="flat__cover-select">
      <% @flat.photos.each do |photo| %>
        <li class="flat__cover-select__item">
          <%= image_tag photo.file.url, class: 'flat__cover-select__item__photo' %>
          <%= f.radio_button :cover_id, photo.id, class: 'flat__cover-select__item__input' %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= f.button :submit, class: 'button button--blue' %>
  <span><%= t('flats.new.or_cancel_html', href: link_to(t('flats.new.or_cancel_href'), root_path)) %></span>
<% end %>

app/views/flats/edit.html.erb
<div class="new-flat__wrapper">
  <h1 class="new-flat__title"><%= t('flats.new.title') %></h1>

  <%= render 'form' %>
</div>

app/views/flats/index.html.erb
<% title t('flats.index.title') %>

<%= render partial: 'flats/index/flat', collection: @flats %>

<%= paginate @flats %>

<% content_for :sidebar do %>
  <%= simple_form_for Search.new, html: { class: 'sidebar__search' } do |f| %>
    <%= f.input :part, as: :select, collection: Search.parts, wrapper_html: { class: 'sidebar__search__input' }, include_blank: false, label: false %>
    <%= f.input :rooms, as: :select, collection: Search.rooms, wrapper_html: { class: 'sidebar__search__input' }, include_blank: false, label: false %>
    <%= f.input :rent, as: :select, collection: Search.prices, wrapper_html: { class: 'sidebar__search__input' }, include_blank: false, label: false %>

    <div class="sidebar__search__input">
      <%= f.submit 'Найти квартиру', class: 'button button--wide button--search' %>
    </div>
  <% end %>
<% end %>

<%= javascript_tag do %>
  mixpanel('All Flats Page Viewed')
<% end %>

app/views/flats/new.html.erb
<div class="new-flat__wrapper">
  <h1 class="new-flat__title"><%= t('flats.new.title') %></h1>

  <%= render 'form' %>
</div>

app/views/flats/show.html.erb
<% title @flat.title %>

<% content_for(:head) do %>
  <%= stylesheet_link_tag 'http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.3/fotorama.css' %>
  <%= javascript_include_tag 'http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.3/fotorama.js' %>
  <%= javascript_include_tag 'http://maps.googleapis.com/maps/api/js?key=AIzaSyDcw2onVUPC_iqXvpLw7V7JHjtCy8Tsahk' %>

  <%= content_tag :meta, nil, name: 'title', content: @flat.title %>
  <%= content_tag :meta, nil, name: 'description', content: @flat.description %>
  <link rel="image_src" href="<%= @flat.cover.file.url.html_safe %>">
<% end %>

<% if user_signed_in? %>
  <% content_for(:editor) do %>
    <div class="editor-panel js-editor-panel" data-flat-id="<%= @flat.id %>">
      <div class="editor-panel__inner">
        <div class="editor-panel__flat-id">
          <span><i class="ss-icon">link</i> <%= @flat.id %></span>
        </div>

        <ul class="editor-panel__actions">
          <li class="editor-panel__actions__item">
            <%= link_to '<i class="ss-icon">edit</i>Редактировать'.html_safe, edit_flat_path(@flat) %>
          </li>

          <li class="editor-panel__actions__item <%= 'editor-panel__actions__item--disabled' if @flat.vk_post_id.present? %>" data-action="share_on_vk">
            <%= link_to '<i class="ss-icon">like</i>Поделиться'.html_safe, '' %>
          </li>

          <li class="editor-panel__actions__item <%= 'editor-panel__actions__item--disabled' if @flat.featured? %>" data-action="feature">
            <%= link_to '<i class="ss-icon">heart</i>На главную'.html_safe, '' %>
          </li>

          <li class="editor-panel__actions__item <%= 'editor-panel__actions__item--disabled' if @flat.rented? %>" data-action="rent">
            <%= link_to '<i class="ss-icon">send</i>Сдать'.html_safe, '' %>
          </li>

          <li class="editor-panel__actions__item <%= 'editor-panel__actions__item--disabled' unless @flat.published? %>" data-action="unpublish">
            <%= link_to '<i class="ss-icon">trash</i>Удалить'.html_safe, '' %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

<%= content_tag_for :article, @flat do %>
  <hgroup>
    <h1 class="flat__address"><%= @flat.title %></h1>

    <span class="flat__rooms"><%= @flat.rooms %></span>,
    <span class="flat__area"><%= "#{@flat.area.round} m<sup>2</sup>".html_safe %></span>
  </hgroup>

  <div class="flat__photos fotorama" data-nav="thumbs" data-keyboard="true">
    <% @flat.photos.each do |photo| %>
      <%= image_tag photo.file.url %>
    <% end %>
  </div>

  <div class="flat__description__wrapper">
    <div class="flat__description">
      <%= simple_format @flat.description %>
    </div>
  </div>

  <div id="map_canvas" style="height: 162px; margin: 0; padding: 0;" data-lat="<%= @flat.latitude %>" data-lng="<%= @flat.longitude %>"></div>
  <%= link_to 'увеличить'.html_safe, '', class: 'js-map-toggle', style: 'color: #222; float: right; margin-top: 5px; font-size: 12px;' %>
<% end %>

<aside class="flat-sidebar">
  <% if @flat.rented? %>
    <section class="flat__rented">
      <h2 class="flat__rented__title"><%= t('flats.rented_oops') %></h2>
      <span><%= t('flats.rented', href: link_to(t('flats.rented_href'), flats_path)).html_safe %></span>
    </section>
  <% else %>
    <span class="flat__rent">
      <!-- i class="ss-icon">tag</i -->
      <%= number_to_currency(@flat.rent, format: '%n', precision: 0) %>
      <small>Kč</small>
    </span>

    <span class="flat__utility"><%= @flat.utility_included ? t('flats.utility_included') : t('flats.utility_not_included') %></span>

    <!-- <section class="flat-sidebar__request-form">
      <%# render 'requests/form' %>
    </section> -->

    <%= link_to t('tickets.new.title'), '#', class: 'button button--blue button--wide new-ticket__opener', data: { remodal_target: 'new_ticket_modal' } %>

    <%= render 'flats/show/similar_flats' %>
  <% end %>

  <!-- section class="flat-sidebar__agent">
    <div class="flat-sidebar__agent__inner">
      <%
        agents = [
          {
            name: 'Яков',
            image: 'iakov.jpg',
            phone: '+420 777 429 900'
          },

          {
            name: 'Адам',
            image: 'adam.jpg',
            phone: '+420 608 700 468'
          }
        ]

        agent = agents.sample
      %>

      <div class="flat-sidebar__agent__photo"><%= image_tag agent[:image] %></div>
      <h2 class="flat-sidebar__agent__name">
        <%= agent[:name] %><span class="flat-sidebar__agent__name__title">, риэлтор</span>
        <span class="flat-sidebar__agent__contact"><%= agent[:phone] %></span>
      </h2>
    </div>
  </section -->

  <!-- ul class="flat-sidebar__share">
    <li>
      <a href="#" class="flat-sidebar__share__item flat-sidebar__share__item--vk js-share-vk">Поделиться</a>
    </li>
  </ul -->
</aside>

<div data-remodal-id="new_ticket_modal" class="remodal berkub-remodal new-ticket" data-cover-image-url="<%= @flat.cover.file.url %>">
  <hgroup class="new-ticket__header new-ticket__cover">
    <h1 class="new-ticket__title"><%= t('tickets.new.title') %></h1>
    <h2 class="new-ticket__subtitle"><%= t('tickets.new.subtitle') %></h2>
  </hgroup>

  <%= render 'tickets/form' %>
  <%= render 'tickets/thanks' %>
</div>

<%= javascript_tag do %>
  mixpanel.track('Flat Page Viewed', { flat_id: <%= @flat.id.to_json %> })

  <% if @flat.featured? %>
    mixpanel.track('Featured Flat Page Viewed', { flat_id: <%= @flat.id.to_json %> })
  <% end %>
<% end %>