config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  namespace :editor do
    resources :flats, except: [:index, :show] do
      post '/share_on_vk', to: 'flats#share_on_vk', on: :member
      post '/feature', to: 'flats#feature', on: :member
      post '/rent', to: 'flats#rent', on: :member
      post '/unpublish', to: 'flats#unpublish', on: :member
    end
  end

  resources :flats do
    get '/match', to: 'flats#mark', on: :member
    get '/share', to: 'flats#share', on: :member
  end

  resources :tickets

  resources :clients
  resources :searches
  resources :requests

  root 'welcome#index'

  get "/:id", to: "pages#show", as: :page
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :requests
  has_many :flats, through: :requests
end

app/models/flat.rb
require 'open-uri'

class Flat < ActiveRecord::Base
  include Shareable

  has_many :photos, dependent: :destroy

  has_many :requests
  has_many :clients, through: :requests

  accepts_nested_attributes_for :photos

  default_scope -> { where(published: true, rented: false).order('created_at desc') }
  scope :published, -> { where(published: true) }
  scope :recent, -> { limit(12) }
  scope :featured, -> { where(featured: true) }
  scope :available, -> { where(rented: false) }

  geocoded_by :location
  after_validation :geocode, if: :address_changed?
  after_validation :geocode, if: :part_changed?

  def self.mark_all_photos
    all.each do |flat|
      flat.mark_photos
    end
  end

  def title
    "#{address}, #{part}"
  end

  def cover
    if cover_id.present? && photos.exists?(cover_id)
      photos.find(cover_id)
    else
      photos.last
    end
  end

  def description
    description_ru.presence ? description_ru : super
  end

  def location
    "#{address}, #{part}"
  end

  def mark_photos
    photos.each do |photo|
      photo.mark!
    end
  end

  def ensure_availability
    return false unless external_source_id.present?

    external_source_page = Nokogiri::HTML(open("http://www.feelhome.cz/pronajem/detail/#{external_source_id}/"))

    if (external_source_page.css('#detailprice').text.strip =~ /pronajato/)
      update_column(:rented, true)
      id
    else
      nil
    end
  end
end

app/models/photo.rb
require 'open-uri'

class Photo < ActiveRecord::Base
  belongs_to :flat

  mount_uploader :file, PhotoUploader

  def mark!
    mark ||= MiniMagick::Image.open("#{Rails.public_path}/mark.jpg")
    remote_photo = MiniMagick::Image.open(self.file.url).write("#{Rails.public_path}/photos/photo-#{id}.jpg")
    photo = MiniMagick::Image.open("#{Rails.public_path}/photos/photo-#{id}.jpg")

    marked_photo = photo.composite(mark, 'jpg') do |c|
      c.gravity 'SouthEast'
      c.geometry 'x+15'
    end

    File.delete("#{Rails.public_path}/photos/photo-#{id}.jpg")

    self.file = marked_photo
    self.marked = true
    save!
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :flat
  belongs_to :client
end

app/models/search.rb
class Search < ActiveRecord::Base
  before_save :sanitise_filters

  class << self
    def parts
      (1..10).to_a.map do |n|
        "Praha #{n}"
      end.unshift('Расположение')
    end

    def rooms
      (1..5).to_a.map do |n|
        # ["#{n}+1", "#{n}+kk"]
        ["#{n}+kk"]
      end.flatten.unshift('Комнаты')
    end

    def prices
      prices_hash = { 'Цена' => 0.0 }
      [10, 15, 20, 25, 30, 35, 40].each do |n|
        prices_hash.merge!("до #{ActionController::Base.helpers.number_to_currency(n * 1000, format: '%n', precision: 0)} Kč" => (n * 1000).to_f)
      end
      prices_hash
    end
  end

  def flats
    filters = {
      part: part,
      rooms: rooms,
      rent: rent
    }

    @flats ||= search(filters)
  end

private

  def sanitise_filters
    self.part = nil if part == 'Расположение'
    self.rent = nil if rent.to_f == 0.0
    self.rooms = nil if rooms == 'Комнаты'
  end

  def search(filters = [])
    flats = Flat.all
    flats = flats.where("part ILIKE '%#{filters[:part]}%'") if filters[:part].present?
    flats = flats.where("rooms LIKE '#{filters[:rooms].first}%'") if filters[:rooms].present?
    flats = flats.where("rent <= #{filters[:rent].to_f}") if filters[:rent].present?
    flats
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :flat
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:mark, :share]
  before_action :set_unscoped_flat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @flats = Flat.all.page(params[:page])
  end

  def new
    @flat = Flat.new
    @flat.published = false
    @flat.save

    redirect_to edit_flat_path(@flat)
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flat_url(@flat)
    else
      render action: :new
    end
  end

  def mark
    @flat.photos.each do |photo|
      photo.mark!
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      respond_to do |format|
        format.html { redirect_to flat_url(@flat) }
        format.json { render json: @flat.to_json }
      end
    else
      respond_to do |format|
        format.html { render action: :edit }
        format.json
      end
    end
  end

  def show
    @request = @flat.requests.build
  end

  def share
    @flat.share_on_vk

    redirect_to flat_url(@flat)
  end

private

  def flat_params
    params.require(:flat).permit(:address, :part, :rooms, :rent, :area, :description, :description_ru, :published, :utility_included, :featured, :rented, :external_source_id, :cover_id, { photos_attributes: [:file] })
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def set_unscoped_flat
    @flat = Flat.unscoped.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  VALID_CHARACTERS = "a-zA-Z0-9~!@$%^&*()#`_+-=<>\"{}|[];',?".freeze

  rescue_from ActionView::MissingTemplate do |exception|
    if exception.message =~ %r{Missing template #{content_path}}
      raise ActionController::RoutingError, "No such page: #{params[:id]}"
    else
      raise exception
    end
  end

  def show
    render template: current_page
  end

protected

  def current_page
    "#{content_path}#{clean_path}"
  end

  def clean_path
    path = Pathname.new("/#{clean_id}")
    path.cleanpath.to_s[1..-1]
  end

  def content_path
    "pages/"
  end

  def clean_id
    params[:id].tr("^#{VALID_CHARACTERS}", '')
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def create
    @request = Request.create(request_params)
    RequestMailer.new_request_notification(@request).deliver

    respond_to :js
  end

private

  def request_params
    params.require(:request).permit(:name, :phone, :email, :availability, :flat_id)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :update]

  def create
    @search = Search.create!(search_params)
    redirect_to @search
  end

  def update
    @search.update(search_params)
    redirect_to @search
  end

  def show
  end

private

  def search_params
    params.required(:search).permit(:rooms, :rent, :part)
  end

  def set_search
    @search = Search.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.save

    TicketMailer.new_ticket_notification(@ticket).deliver
  end

private

  def ticket_params
    params.require(:ticket).permit(:name, :phone, :email, :body, :flat_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @featured_flats = Flat.unscoped.published.available.limit(4).featured.order('created_at desc')
    @recent_flats = Flat.recent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title do
      page_title
    end
  end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_fonts.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=cyrillic-ext,latin,latin-ext' rel='stylesheet' type='text/css'>

app/views/layouts/_mixpanel.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2.2.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("bf6adcef5d33245a96d8a60d847ecbd5");</script><!-- end Mixpanel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? "#{yield(:title)} — Berkub" : 'Berkub' %></title>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/fonts' %>
  <%= render 'layouts/mixpanel' %>

  <%= yield(:head) %>
</head>
<body class="<%= "#{controller_name} #{action_name}" %>">

<div class="container">
  <!-- header class="header">
    <div class="header__logo"><%= link_to_unless_current image_tag('logo.png'), root_path %></div>

    <ul class="header__nav">
      <li class="header__nav__link"><%= link_to t('flats.index'), flats_path %></li>
      <li class="header__nav__link"><%= link_to t('flats.new.title'), new_flat_path %></li>
    </ul>
  </header -->

  <aside class="sidebar">
    <div class="sidebar__logo"><%= link_to image_tag('logo.png'), root_path %></div>

    <nav class="sidebar__menu__wrapper">
      <ul class="sidebar__menu">
        <li class="sidebar__menu__item"><%= link_to t('flats.index.title'), flats_path %></li>
      </ul>
    </nav>

    <%= yield :sidebar %>

    <ul class="sidebar__footer">
      <li class="sidebar__footer__item"><%= link_to t('pages.about.title'), page_path('about') %></li>
      <!-- li class="sidebar__footer__item"><%= link_to 'Условия использования', '' %></li -->
      <li class="sidebar__footer__item js-contact-link"><%= mail_to 'hello@berkub.com?Subject=Hi', t('contact_us') %></li>
      <li class="sidebar__footer__item sidebar__footer__item--copy"><%= "&copy; #{Time.now.year} Berkub".html_safe %></li>
    </ul>
  </aside>

  <div class="content">
    <%= yield %>
  </div>

  <!-- footer class="footer">
    <div class="footer__copy">
      <span>&copy; <%= Time.now.year %> Berkub</span>
    </div>
  </footer -->
</div>

<%= yield(:editor) %>

<%= render 'layouts/clicky' %>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? "#{yield(:title)} — Berkub" : 'Berkub' %></title>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/fonts' %>
  <%= render 'layouts/mixpanel' %>

  <%= yield(:head) %>
</head>
<body class="<%= "#{controller_name} #{action_name}" %>">

<div class="container">
  <header class="header">
    <div class="header__logo"><%= link_to_unless_current image_tag('logo_white.png'), root_path %></div>

    <ul class="header__nav">
      <li class="header__nav__link"><%= link_to t('flats.index.title'), flats_path %></li>
      <li class="header__nav__link"><%= link_to t('pages.about.title'), page_path('about') %></li>
    </ul>
  </header>

  <div class="welcome__cover">
    <div class="welcome__cover__inner">
      <hgroup>
        <h1>Найди свой новый дом</h1>
        <h2>“Home Is Where The Heart Is”</h2>
      </hgroup>
    </div>

    <div class="welcome__search">
      <!-- <div class="welcome__search__inner"></div> -->
      <%= render 'search' %>
    </div>
  </div>

  <%= yield %>
</div>

<%= render 'layouts/clicky' %>
</body>
</html>

app/views/pages/about.html.erb
<% title t('pages.about.title') %>

<div class="about__title">
  <div class="about__title__inner">
    <p>Исходя из предыдущего опыта работы в нескольких чешских агентствах недвижимости, мы решили создать свое, отличное от всех остальных агентств, в котором постарались устранить все недочеты, доставлявшие проблемы как клиентам, так и нам самим. Основной упор делается на долгосрочную аренду элитных квартир иностранному населению Праги. Мы расширяем границы представления о недвижимости.</p>
    <p><strong>Bérkub</strong> — это качество, а не количество.</p>

    <%= link_to t('welcome.find_your_home'), flats_path, class: 'button button--about' %>
  </div>
</div>

<%= javascript_tag do %>
  mixpanel.track('About Page Viewed')
<% end %>